<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-19T15:46:41 IST" name="Suite" finished-at="2024-12-19T15:48:25 IST" duration-ms="103472">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.loginErrorValidation()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" name="loginErrorValidation" class="sandeepkumar.Tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" name="submitOrder" class="sandeepkumar.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-12-19T15:46:41 IST" name="Error Validation Test" finished-at="2024-12-19T15:48:15 IST" duration-ms="93986">
      <class name="sandeepkumar.Tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:46:42 IST" name="launchApplication" finished-at="2024-12-19T15:47:05 IST" duration-ms="22882" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:47:05 IST" name="ProductErrorValidation" finished-at="2024-12-19T15:47:27 IST" duration-ms="22248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:47:27 IST" name="tearDown" finished-at="2024-12-19T15:47:28 IST" duration-ms="1141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:47:28 IST" name="launchApplication" finished-at="2024-12-19T15:47:37 IST" duration-ms="8753" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:47:37 IST" name="loginErrorValidation" finished-at="2024-12-19T15:47:43 IST" duration-ms="6297" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at sandeepkumar.Tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:47:43 IST" name="tearDown" finished-at="2024-12-19T15:47:46 IST" duration-ms="2704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:47:46 IST" name="launchApplication" finished-at="2024-12-19T15:48:02 IST" duration-ms="15947" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:48:02 IST" name="loginErrorValidation" finished-at="2024-12-19T15:48:07 IST" duration-ms="5778" status="FAIL">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.205)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [224b7cddd404e20fe6484f99d952dc2c, getElementText {id=f.0B41CDAB9A6E0E6E7C71FE6776F60299.d.7B580AAE637881149EA157CD10044D63.e.16}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.205, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\ASUS\AppData\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:52331}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:52331/devtoo..., se:cdpVersion: 131.0.6778.205, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (224b7cddd404e20fe6484f99d952dc2c)] -> css selector: [class*='flyInOut']]
Session ID: 224b7cddd404e20fe6484f99d952dc2c]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.205)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [224b7cddd404e20fe6484f99d952dc2c, getElementText {id=f.0B41CDAB9A6E0E6E7C71FE6776F60299.d.7B580AAE637881149EA157CD10044D63.e.16}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.205, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\ASUS\AppData\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:52331}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:52331/devtoo..., se:cdpVersion: 131.0.6778.205, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (224b7cddd404e20fe6484f99d952dc2c)] -> css selector: [class*='flyInOut']]
Session ID: 224b7cddd404e20fe6484f99d952dc2c
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:191)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.getText(Unknown Source)
at sandeepkumar.pageObject.LandingPage.geterrorMessage(LandingPage.java:53)
at sandeepkumar.Tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:sandeepkumar.Tests.ErrorValidation@41330d4f]" started-at="2024-12-19T15:48:13 IST" name="tearDown" finished-at="2024-12-19T15:48:15 IST" duration-ms="2348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- sandeepkumar.Tests.ErrorValidation -->
    </test> <!-- Error Validation Test -->
    <test started-at="2024-12-19T15:46:41 IST" name="Submit Order Test" finished-at="2024-12-19T15:48:25 IST" duration-ms="103472">
      <class name="sandeepkumar.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:46:43 IST" name="launchApplication" finished-at="2024-12-19T15:47:04 IST" duration-ms="20681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:47:04 IST" name="submitOrder" data-provider="getData" finished-at="2024-12-19T15:47:30 IST" duration-ms="25745" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sandy@123, product=ADIDAS ORIGINAL, email=sandeepkumar123@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:47:30 IST" name="tearDown" finished-at="2024-12-19T15:47:34 IST" duration-ms="3991" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:47:34 IST" name="launchApplication" finished-at="2024-12-19T15:47:46 IST" duration-ms="12043" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:47:46 IST" name="submitOrder" data-provider="getData" finished-at="2024-12-19T15:48:06 IST" duration-ms="19763" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Rahul@123, product=IPHONE 13 PRO, email=rahulkumar123@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:48:06 IST" name="tearDown" finished-at="2024-12-19T15:48:08 IST" duration-ms="2812" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:48:08 IST" name="launchApplication" finished-at="2024-12-19T15:48:20 IST" duration-ms="11480" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:48:20 IST" name="OrderHistoryTest" finished-at="2024-12-19T15:48:25 IST" depends-on-methods="sandeepkumar.Tests.SubmitOrderTest.submitOrder" duration-ms="4767" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:sandeepkumar.Tests.SubmitOrderTest@72bc6553]" started-at="2024-12-19T15:48:25 IST" name="tearDown" finished-at="2024-12-19T15:48:25 IST" duration-ms="281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- sandeepkumar.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
